### ISSUE TITLE
Support command line flag for input and output files

### ISSUE THREAD

**Issue by ZevEisenberg** [joshdholtz/crunchygif#8]
That would let you use it in all kinds of cool workflows. You could also make command line args for the various parameters, but just using the settings that are specified in the app is a good start.

**Comment by joshdholtz** [comment]
@ZevEisenberg In `1.1.0`, this can be done by 👆

```sh
open ~/Desktop/screen_recording_1.mov -a /Applications/CrunchyGIF.app
```
